build a portfolio header page with two sections
Dinma-Faith/Portfoilio-Site pull request #1
Opened 2022-02-09 20:51 UTC by Dinma-Faith

2022-02-10 10:41 UTC, Hope1226 requested changes
Hi @Dinma-Faith  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :stop_sign: 
![](https://c.tenor.com/r8iFXcSVmWoAAAAd/hang-in-there-champ.gif)
## Why this happened :question: :question: :question: 
You have submitted a project, that is not compliant with some of the project general requirements, please kindly make sure to address the below remarks and resubmit for review:

- [ ] Please make sure that all linter checks are passing, currently, one (Stylelint) out of three is failing, follow the [hints](https://github.com/Dinma-Faith/Portfoilio-Site/runs/5139114663?check_suite_focus=true) to pass it.
- [ ] Please make sure `README` file is descriptive and is customized similar to or based on [this template ](https://github.com/microverseinc/readme-template) and contains all sections as it is shown in the template.
- [ ] Please  make sure your PR has short and descriptive summary

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-10 16:52 UTC, Dinma-Faith-zz commented
![code review ms](https://user-images.githubusercontent.com/69027469/153456306-be16a2ff-4949-45c2-b87e-a8b02800b78e.png)

2022-02-10 16:53 UTC, Dinma-Faith commented
i have done the corrections but still having webhint err

2022-02-11 14:11 UTC, BenMukebo requested changes
### Hi **@Dinma**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!


## STATUS: CHANGES REQUESTED  ♻️ 

_Please Check the comments under the review and make all required changes_

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)


- [ ] Kindly, Add a descriptive README file to your project as required please use this [template](https://github.com/microverseinc/readme-template) You can copy past but remember to customize it to your project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

** ⚠️  _Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 14:11 UTC, BenMukebo commented on index.html
> +      </header>
- [ ] Please, the logo should be wrapped inside an `a` tag, as it will be used for the user to return to the home page later on, for HTML best practice, consider wrapping the hamburger icon inside the `nav` tag, since it will contain navigation element later in the project. consider 
kindly, make sure, the container `header` uses `flexbox` to align elements inside; the logo and the navbar.

2022-02-11 14:11 UTC, BenMukebo commented on style.css
> +  background-size: cover;
- [ ] Kindly, it should be better if you don't set the background image to the body, later on in the project, each section may have its own background, you should consider creating a specific section container you need to apply your styling on. let's go and fix this.

2022-02-11 14:11 UTC, BenMukebo commented on index.html
> +        <h3 class="connection">LETS CONNECT</h3>
- [ ] Great job on wrapping this whole in one section, but I think the `h3` LET'S CONNECT should either be a `button` or an `a` tag, please consider changing that too.
- [ ] The main title I'm Dinma should be an `<h1>`, please correct that.
- [ ] consider using `flexbox` property to align element for this section

2022-02-11 14:11 UTC, BenMukebo commented on index.html
> +        </div>
- [ ] Please, make sure the list of icons is wrapped in a `ul` and each icon in a`li`, consider adding a link `a` tag for each icon.

2022-02-11 14:11 UTC, BenMukebo commented on style.css
> +}
- [ ]  These properties broke your page on the mobile version, please follow this [link](https://www.youtube.com/watch?v=NeThtWARdnY&t=2s) to have a short idea on how to start a web application from mobile-first, after you can you use this as a reference to correct this approach you used before. 😄 , see images below

- [ ]  YOUR DESIGN ⬇️ 

<img width="320" alt="yud" src="https://user-images.githubusercontent.com/79058364/153604995-5995493d-7856-4a05-95e6-1d67d9cb37fd.png">

- [ ] FIGMA DESIGN 🔽 

<img width="256" alt="da" src="https://user-images.githubusercontent.com/79058364/153605229-2547f635-271d-452a-9775-b1bc4bfe7049.png">

- [ ] Please adjust your webpage (`margin, padding, font-size, colors, images`) to match the original design.

2022-02-11 20:30 UTC, merged

2022-02-11 21:13 UTC, RolandM99 reviewed
# STATUS : CHANGES REQUESTED

Hi @Dinma-Faith , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

### To highlight 💯 
- Good commit message ✔️
- No Linter errors ✔️
- Follow Github flow ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 21:13 UTC, RolandM99 commented on index.html
> +      </header>
- [ ] Kindly implement the features requested by the previous reviewer. your logo still has a header` h1` tag . Please, change it with an anchor `<a>` tag

2022-02-11 21:13 UTC, RolandM99 commented on index.html
> +        <h3 class="connection">LETS CONNECT</h3>
- [ ] Please, make sure that you implement the requests provided by the previous reviewer. 'LET'S CONNECT' still has a header tag and the main title should have a header tag `h1`. let's rock, fix them 🧑‍🔧

2022-02-11 21:13 UTC, RolandM99 commented on index.html
> +        </div>
- [ ] Kindly, implement this request from the previous reviewer.

2022-02-11 21:13 UTC, RolandM99 commented on style.css
> +}
God job so far by implementing some project requirements as expected. But to make your design very similar to the Figma design, kindly adjust your webpage ( `margin, padding, colors, fonts and images` ) as requested by the previous reviewer.

2022-02-12 06:14 UTC, Dinma-Faith commented
Hello! Please I really don’t know how to go about making this change. I
already closed my PR . Meaning if I have to make changes I would have to
request a new pull request right? And the project requires using a single
PR. I really don’t know what to do now. I need your suggestions please.

Regards

On Fri, 11 Feb 2022 at 10:13 PM, Roland MWEZE ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> STATUS : CHANGES REQUESTED
>
> Hi @Dinma-Faith <https://github.com/Dinma-Faith> ,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> To highlight 💯
>
>    - Good commit message ✔️
>    - No Linter errors ✔️
>    - Follow Github flow ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/Dinma-Faith/Portfoilio-Site/pull/1#discussion_r804998105>
> :
>
> > +      <header class="main-header">
>
> +          <h1>My Logo</h1>
>
> +            <span class="toggle"><i class="fa-solid fa-bars"></i></span>
>
> +      </header>
>
>
>
>    - Kindly implement the features requested by the previous reviewer.
>    your logo still has a header h1 tag . Please, change it with an anchor
>    <a> tag
>
> ------------------------------
>
> In index.html
> <https://github.com/Dinma-Faith/Portfoilio-Site/pull/1#discussion_r805001558>
> :
>
> > +    <section class="section1">
>
> +      <div class="section1-content" >
>
> +        <h2>I'm Dinma <br>  Glad to see you!</h2>
>
> +        <p>I’m a software developer! I can help you build a product , feature or website Look through<br> some of my work and experience! If you like what you see and have a project you need <br>coded don’t hestiate to contact me.</p>
>
> +        <!--Social Media Section-->
>
> +        <h3 class="connection">LETS CONNECT</h3>
>
>
>
>    - Please, make sure that you implement the requests provided by the
>    previous reviewer. 'LET'S CONNECT' still has a header tag and the main
>    title should have a header tag h1. let's rock, fix them 🧑‍🔧
>
> ------------------------------
>
> In index.html
> <https://github.com/Dinma-Faith/Portfoilio-Site/pull/1#discussion_r805002708>
> :
>
> > +        <div class="social-media">
>
> +          <img src="./img/social-media-icons.jpg" alt="">
>
> +        </div>
>
>
>
>    - Kindly, implement this request from the previous reviewer.
>
> ------------------------------
>
> In style.css
> <https://github.com/Dinma-Faith/Portfoilio-Site/pull/1#discussion_r805005243>
> :
>
> > +
>
> +.section1-content {
>
> +  position: absolute;
>
> +  top: 50%;
>
> +  left: 50%;
>
> +  transform: translate(-50%, -50%);
>
> +}
>
>
> God job so far by implementing some project requirements as expected. But
> to make your design very similar to the Figma design, kindly adjust your
> webpage ( margin, padding, colors, fonts and images ) as requested by the
> previous reviewer.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dinma-Faith/Portfoilio-Site/pull/1#pullrequestreview-880668902>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQOUNDKOPYZOZC75LEAYHSLU2V3YNANCNFSM5N6TPY4Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>